name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 3.1.301

    - name: Restore dependencies
      run: dotnet restore .

    - name: Publish
      run: dotnet publish ./src/JohanBos.ScaledActivitied.Function/JohanBos.ScaledActivities.Function.csproj --output ./package

    - uses: azure/login@v1.3.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run ARM deploy
      id: infra
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/template.json
        parameters: ./infra/parameters-test.json

    - name: Deploy
      uses: Azure/functions-action@v1.4.0
      with:
        app-name: ${{ steps.infra.outputs.functionName }}
        package: ./package
