name: Deploy

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ] # testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Restore dependencies
      run: dotnet restore ./src

    - name: Publish
      run: dotnet publish ./src --output ./package

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra/template.json
        parameters: ./infra/parameters.json

    - name: Deploy
      uses: Azure/functions-action@v1.1.8
      with:
        app-name: scaled-activities-eus2
        package: ./package
